server:
  port: 9031

spring:
  elasticsearch:
    host: 127.0.0.1
    port: 9200
    username: elastic  # Elasticsearch 用户名
    password: 20030706  # Elasticsearch 密码
  application:
    name: blog-article
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: lrh,903.520hhhh
    url: jdbc:mysql://sh-cdb-pezvivda.sql.tencentcdb.com:63950/article?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  redis:
    host: cd-crs-0q0ceb8t.sql.tencentcdb.com
    port: 29577
    password: lrh,903.520hhhh

mybatis-plus:
  mapper-locations: classpath*:xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0