server:
  port: 9031

spring:
  elasticsearch:
    host: 1.95.153.163
    port: 9200
    username: elastic
    password: NJLnewr4nZMuXInvcKMK
  application:
    name: blog-article
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1800000
    username: root
    password: lrh,903.520hhhh
    url: jdbc:mysql://sh-cdb-pezvivda.sql.tencentcdb.com:63950/article?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  redis:
    host: 43.141.197.88
    port: 29577
    password: lrh,903.520hhhh
rocketmq:
  name-server: localhost:9876
  producer:
    #生产者组名
    group: article-group
    topic: article-topic
    #消息发送的超时时间，毫米级别，默认为3S
    send-message-timeout: 60000
    #最大的消息限制 默认为128K
    max-message-size: 4194304
    #同步消息发送失败重试次数
    retry-times-when-send-failed: 3
    #异步消息发送失败重试的次数
    retry-times-when-send-async-failed: 3
  consumer:
    group: article-group
    topic: article-topic
mybatis-plus:
  mapper-locations: classpath*:xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0