server:
  port: 9031

spring:
  application:
    name: blog-article
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: lrh,903.520hhhh
    url: jdbc:mysql://127.0.0.1:3306/article?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  redis:
    host: 192.168.29.200
    port: 6379
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

mybatis-plus:
  mapper-locations: classpath*:xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0