server:
  port: 7001

spring:
  application:
    name: blog-gateway
  redis:
    host: cd-crs-0q0ceb8t.sql.tencentcdb.com
    port: 29577
    password: lrh,903.520hhhh
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=gateway-env, blog-gateway
      routes:
        - id: user
          uri: lb://blog-user
          predicates:
            - Path=/api/user/**

        - id: identity
          uri: lb://blog-identity
          predicates:
            - Path=/api/role/**

        - id: article
          uri: lb://blog-article
          predicates:
            - Path=/api/article/**,/api/comment/**

        - id: oss
          uri: lb://blog-oss
          predicates:
            - Path=/api/oss/file/**

        - id: message
          uri: lb://blog-message
          predicates:
            - Path=/api/message/**

        - id: message-netty
          uri: lb://blog-message-netty
          predicates:
            - Path=/api/message-netty/**

        - id: netty
          uri: lb://blog-netty
          predicates:
            - Path=/api/netty