server:
  port: 7001

spring:
  application:
    name: blog-gateway
  redis:
    host: 192.168.29.200
    port: 6379
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    gateway:
      default-filters:
        - AddRequestHeader=gateway-env, blog-gateway
      routes:
        - id: user
          uri: lb://blog-user
          predicates:
            - Path=/api/user/**

        - id: identity
          uri: lb://blog-identity
          predicates:
            - Path=/api/role/**