server:
  port: 7001

spring:
  application:
    name: blog-gateway
  redis:
    host: 106.53.50.195
    port: 6379
    password: lrh,903.520hhhh
  cloud:
    nacos:
      discovery:
        server-addr: 106.53.50.195:8848
        username: nacos
        password: nacos
    gateway:
      default-filters:
        - AddRequestHeader=gateway-env, blog-gateway
      routes:
        - id: user
          uri: lb://blog-user
          predicates:
            - Path=/api/user/**

        - id: identity
          uri: lb://blog-identity
          predicates:
            - Path=/api/role/**

        - id: article
          uri: lb://blog-article
          predicates:
            - Path=/api/article/**,/api/comment/**
